### ISSUE TITLE
Option to download plugins via url

### ISSUE THREAD

**Issue by Janl1** [itzg/docker-bungeecord#10]
It would be great if the bungeecord image would have the same support for the "-e MODS=" parameter included in the minecraft server image just for the plugin folder.
In addition the override parameter would be helpful as well.

Thanks

**Comment by itzg** [comment]
Sorry for the delay in responding. Yes, that sounds like a great idea. I'm totally open to PRs if you want to help out with that.

**Comment by itzg** [comment]
Fixed in #11
