### ISSUE TITLE
Autopause support with multiple servers

### ISSUE THREAD

**Issue by erahhal** [itzg/docker-bungeecord#105]
I've got a setup with three servers behind bungeecord, connected with portals.  If autopause is set for the three servers, coming into one will unpause it, but then the other servers look disconnected when trying to enter the portals across them.  Is there a way to have bungeecord wake all paused servers at once if any server is connected to?  Also any way to show a message to users that isn't an error when the server is starting up, similar to [SleepingServerStarter](https://raw.githubusercontent.com/vincss/mcsleepingserverstarter/master/views/res/sleepingserver.png)?  Thanks for the nice docker images btw.

**Comment by itzg** [comment]
That request seems valid, but this image only wraps bungeecord, etc with upgradable automation. It does not provide any functionality after kicking off the respective jar file with Java.

Perhaps sleeping server starter or a plugin can support intercepting paused servers and/or coordinating unpausing.

**Comment by erahhal** [comment]
Seems reasonable, thanks.
