### ISSUE TITLE
Using Waterfall doesn't download RCON plugin

### ISSUE THREAD

**Issue by SunFlea** [itzg/docker-bungeecord#106]
When using the `TYPE=WATERFALL` environment variable the [`run-bungeecord.sh`](https://github.com/itzg/docker-bungeecord/blob/master/run-bungeecord.sh) script no longer downloads the required RCON plugin. I suspect it happens [here](https://github.com/itzg/docker-bungeecord/blob/1a6fe3c793239c26606948629c10d3fd538712e2/run-bungeecord.sh#L292).

**Comment by itzg** [comment]
Is it compatible with Waterfall?

**Comment by SunFlea** [comment]
Doesn't [`ENABLE_RCON`](https://github.com/itzg/docker-bungeecord/blob/1a6fe3c793239c26606948629c10d3fd538712e2/README.md#environment-settings) mention `WATERFALL`?

**Comment by itzg** [comment]
Yes it does 😀 It's been a while since I have looked at that. 

That logic definitely needs to be fixed then.
