### ISSUE TITLE
bungeecord Type Velocity, can't connect to RCON CLI. Throws i/o timeout

### ISSUE THREAD

**Issue by drloloto** [itzg/docker-bungeecord#115]
I'm trying to setup a multi minecraft sever with most of your repos compined in one docker-compose file.

But now I'm stuck with the RCON connection for my velocity server. RCON to both other server work flawless. 

It's quite easy to reproduce even with the given velocity config "docs/docker-compose-velocity.yml"

Am I missing something?
Is it even possible to connect directly to RCON of the velocity proxy?
[mc_log.txt](https://github.com/itzg/docker-bungeecord/files/9622823/mc_log.txt)
[proxy_log.txt](https://github.com/itzg/docker-bungeecord/files/9622824/proxy_log.txt)
[terminal_command.txt](https://github.com/itzg/docker-bungeecord/files/9622850/terminal_command.txt)

**Comment by itzg** [comment]
That's strange since the plugin seems to bind correctly:

```
[05:54:27 INFO] [velocityrcon]: Binding rcon to address: /0.0.0.0:25575
```

and then the log seems to show where rcon-cli attempted to connect;

```
[05:56:45 INFO] [velocityrcon]: Rcon connection from [/127.0.0.1:36226]
```

I wonder if https://github.com/UnioDex/VelocityRcon would have any ideas.

**Comment by drloloto** [comment]
I ditched rcon for now. I'll post on https://github.com/UnioDex/VelocityRcon anyways
