### ISSUE TITLE
Health status

### ISSUE THREAD

**Issue by Carlosgrr** [itzg/docker-bungeecord#118]
I just tried to run a velocity server using the following docker-compose file:
```
version: '3.8'
services:
  velocity:
    image: itzg/bungeecord
    container_name: velocity
    restart: always
    environment:
      TYPE: VELOCITY
    volumes:
      - ./velocity:/server
    ports:
      - 25568:25568
```
As you can see it is pretty bare bones, the container itself is running perfectly as the logs show:
```
[22:03:45 INFO]: Loading plugins...
[22:03:45 INFO]: Loaded 0 plugins
[22:03:45 INFO]: Listening on /0.0.0.0:25568
[22:03:45 INFO]: Done (4.81s)!
```
But the health of the container is marked as unhealthy
```
$ docker ps

26f836e33f42 itzg/bungeecord  "/usr/bin/run-bungee…" 4 minutes ago   Up 4 minutes (unhealthy) 
  0.0.0.0:25568->25568/tcp, :::25568->25568/tcp
```
It would be awesome if this container could be fixed to correctly report it's status, just like the itzg/minecraft-server container does.
Is it some configuration I am missing on my end, or is this issue an enhancement request?

<p align="center">
Either way, thanks in advance.<br>
Gustavo
</p>

**Comment by itzg** [comment]
It looks like it does the health check against port 25577 which is the default for the env var `SERVER_PORT`. If set that variable to 25568 to match your config, then that should fix it.

**Comment by Carlosgrr** [comment]
That fixed it for me, but I believe this issue should be left open, just for the other users, that might happen to get the same problem.

**Comment by itzg** [comment]
I'm glad that resolved it. 

Issues can be found just as easily when they're closed and I'd prefer not to just leave this open forever.

**Comment by LittleGiqnt** [comment]
Sorry for bumping but this helped me, thanks!

**Comment by itzg** [comment]
I'm glad to hear it helped @LittleGiqnt 

That reminds me, it's probably time to close the issue -- but remains just as discoverable.
