### ISSUE TITLE
SPIGET_PLUGINS not following redirects to Bukkit download page.

### ISSUE THREAD

**Issue by scottmando2000** [itzg/docker-bungeecord#120]
When using the SPIGET_PLUGINS, the Spiget API returns a 503.
Upon this error, the container exists.

**Comment by itzg** [comment]
Can you provide the value you passed to SPIGET_PLUGINS and the logs?

It might be temporary since https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

**Comment by itzg** [comment]
Thanks.

I am now wondering why you titled the issue "Incorrect Spiget URL"? Referring to

https://spiget.org/documentation/#!/resources/get_resources_resource_download

What is incorrect about `https://api.spiget.org/v2/resources/96062/download`?

The actual problem I see is that particular resources incorrectly redirects to `https://dev.bukkit.org/projects/punish-manager/files/4293465` which is not a valid file download, but instead a bukkit page.

**Comment by itzg** [comment]
Thanks, but title still isn't quite correct. The redirect is processed correctly but leads to the plugin page and not a CDN download URL. 

The solution is it needs to bring over

https://github.com/itzg/docker-minecraft-server/blob/906e6787ae57d426b65e9fe78e043f570aab6d4f/scripts/start-spiget#L98toL105

to clarify that some plugins provide unusable download links and instead need to be manually downloaded.
