### ISSUE TITLE
No response from RCON-CLI

### ISSUE THREAD

**Issue by IntangibleW** [itzg/docker-bungeecord#122]
![屏幕截图_20230225_222553](https://user-images.githubusercontent.com/43871076/221362205-fd280776-68c0-4561-b0ed-88083b7c45b6.png)
I ran the commands above but nothing it doesn't show any output
I suspect that I set up Rcon incorrectly

**Comment by itzg** [comment]
The startup seems to default to version 1.1 here

```
RCON_VELOCITY_JAR_URL=https://github.com/UnioDex/VelocityRcon/releases/download/v${RCON_VELOCITY_JAR_VERSION}/VelocityRcon.jar
```

So perhaps try a newer version, if available, for `RCON_VELOCITY_JAR_VERSION`. If that works then the I can update the default or it can be PR'ed.

**Comment by IntangibleW** [comment]
The newest version v1.1 seems don't solve my problem

**Comment by itzg** [comment]
Not surprising it didn't make a difference since I already pointed out that 1.1 is the current default. 

I would recommend reporting an issue at https://github.com/UnioDex/VelocityRcon

**Comment by IntangibleW** [comment]
There is already a issue with this:
https://github.com/UnioDex/VelocityRcon/issues/6
However, thanks a lot.
