### ISSUE TITLE
Modrinth Plugin Support

### ISSUE THREAD

**Issue by mintdaniel42** [itzg/docker-bungeecord#125]
Hello,
it's me again :smiley:. Modrinth does support [Bungeecord, Velocity and Waterfall plugins](https://modrinth.com/plugins?g=categories:%27bungeecord%27&g=categories:%27velocity%27&g=categories:%27waterfall%27) and it would be great to have the capability to download plugins directly from Modrinth as it is possible with the [docker-minecraft-server](https://github.com/itzg/docker-minecraft-server#auto-download-mods-and-plugins-from-modrinth).
Yours Sincerely
Daniel

**Comment by itzg** [comment]
Thanks for pointing that out, since I didn't realize they included those. Since the bulk of the complexity is implemented in mc-image-helper, then that should be fairly easy to bring over. 

If you're interested in PR'ing that, then I'd be very open to that.
