### ISSUE TITLE
RCON environment variables don't get into the config file

### ISSUE THREAD

**Issue by zurvan2** [itzg/docker-bungeecord#126]
After setting ENABLE_RCON, RCON_PORT and RCON_PASSWORD on the container, the resulting config file doesn't get the port and password set correctly. 

inside the container: 
```
bungeecord@waterfall-cffc9b745-cvqfk:~$ cat plugins/bungee-rcon/config.yml
# Port you want RCON to listen
port: ${PORT}
# Password you want to authenticate connection with
password: ${PASSWORD}
# This can be used if you want RCON response to be (not) colored
colored: false
bungeecord@waterfall-cffc9b745-cvqfk:~$ echo $RCON_PORT
9001
bungeecord@waterfall-cffc9b745-cvqfk:~$ echo $RCON_PASSWORD
mypass
```

I assume the `sed` commands are not quite right. 

also, strangely, /template/rcon-config.yml still exists even though the run-bungeecord.sh script is trying to remove it. Not sure if that's relevant.

**Comment by itzg** [comment]
Good find. I agree something is strange with the combo of sed and rm operations there. I'm not sure why an in-line sed operation is even being used when it could just process the template and output to the destination file.
