### ISSUE TITLE
Wont acknowledge custom jars unless undocumented $BUNGEE_JAR is defined 

### ISSUE THREAD

**Issue by sfxworks** [itzg/docker-bungeecord#14]
As my work to create charts continue, I came across an issue when trying to specify a custom bungee jar, like FlameCord.jar. The [documentation](https://github.com/itzg/docker-bungeecord#environment-settings) appears to say that I only need $BUNGEE_JAR_URL, but it appears to not run unless [BUNGEE_JAR](https://github.com/itzg/docker-bungeecord/blob/master/run-bungeecord.sh#L5) is defined.

**Comment by itzg** [comment]
I was just cleaning up some variable handling in the startup script and was wondering if your scenario might work better now. How were you attempting to reference the FlameCord.jar?

**Comment by itzg** [comment]
The enhancement, thanks to @orblazer , is now available on Docker Hub.
