### ISSUE TITLE
Won't detect variables in Environment

### ISSUE THREAD

**Issue by therealeldaria** [itzg/docker-bungeecord#15]
So I wanted to update to latest version of Bungecord so tried ot add the variables to my docker-compose.

> mcb-bungee:
>      container_name: mcb-bungee
>      image: itzg/bungeecord
>      ports:
>        - "25565:25577"
>        - "127.0.0.1:1030:1025"
>      volumes:
>        - "./mcb-bungee/server:/server"
>        - "./mcb-bungee/plugins:/plugins"
>        - "./mcb-bungee/config:/config"
>      environment:
>        BUNGEE_JOB_ID: "lastStableBuild"
>        BUNGEE_BASE_URL: "https://ci.md-5.net/job/BungeeCord"
>        BUNGEE_JAR_URL: "${BUNGEE_BASE_URL}/${BUNGEE_JOB_ID}/artifact/bootstrap/target/BungeeCord.jar"
>        BUNGEE_JAR: "BungeeCord.jar"
>      restart: unless-stopped
>      networks:
>        - mc
>      depends_on:
>        - mcdb
> 

However when the server starts it complains that the variables are not set.

> The BUNGEE_BASE_URL variable is not set. Defaulting to a blank string.
> The BUNGEE_JOB_ID variable is not set. Defaulting to a blank string.
> Recreating mcb-bungee ... done                                                                                                                                                            
> 

And then it still complains in the log about beeing outdated.

> *** Warning, this build is outdated ***
> *** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
> *** You will get NO support regarding this build ***
> *** Server will start in 10 seconds ***
>

**Comment by itzg** [comment]
Apparently the previous startup script didn't allow for a way to easily upgrade the jar without manually removing the previously downloaded one. If you docker pull the latest image, I have now added an optional variable `BUNGEE_JAR_REVISION` that can be used to trigger a re-download. It is documented in a newly refactored section:

https://github.com/itzg/docker-bungeecord#optional-environment-settings

**Comment by therealeldaria** [comment]
Worked like a charm, thanks.
