### ISSUE TITLE
Request: Script similar to mc-send-to-console

### ISSUE THREAD

**Issue by bitter-geek** [itzg/docker-bungeecord#154]
Hi there! I'm having a heck of a time with RCON working (specifically with [Velocity](https://github.com/ygtdmn/VelocityRcon/issues/6)) which isn't a problem on your end, but I'm wondering: on your minecraft-server image you have a `mc-send-to-console` script. Can a similar script be added to this image? Maybe it's already there and I'll be embarrassed when you point it out but, if not, it would really help me to have something like that as a workaround for RCON not working.

Thanks!

**Comment by itzg** [comment]
Sorry for not getting back to you sooner. The rcon plugin used is https://github.com/ygtdmn/VelocityRcon and I checked there aren't any updates available there. 

That "send to console" hasn't been the most reliable mechanism either so I'm hesitant to introduce a new maintenance burden. On the flip side it's just a script to copy that will simply work or not. 

A PR would be fantastic.
