### ISSUE TITLE
Support more Java version

### ISSUE THREAD

**Issue by MartenM** [itzg/docker-bungeecord#159]
Currently running into an issue where I use one of the newer Java versions for creating a plugin.
This results in the following error: 

```
xxx has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

It would be nice if images for newer java versions could be added.

Thanks for maintaining this repository!

**Comment by itzg** [comment]
I can add support for a Java 21 build which will cover that class file version.

**Comment by MartenM** [comment]
That would be epic! 

No need to hurry though. Fixed it by building for a lower version.
Maybe you can automate something like 'latest SDK'.

**Comment by itzg** [comment]
> Maybe you can automate something like 'latest SDK'. 

I'm not sure what you mean exactly. Java 17 was purposely chosen as "latest" since that is what Mojang bundles with latest Minecraft version.

I'll add Java 21 since that's the latest LTS.
