### ISSUE TITLE
BungeeCord can't see Users real IP Adress

### ISSUE THREAD

**Issue by Jupiops** [itzg/docker-bungeecord#16]
Hey there,

I am using your image for my networks BungeeCord instance and I'd like that bungeecord can see the real IP adress of the User for banning reasons and that stufft.

I already tried to disable the userland-proxy but this didn't solve the problem.
All users are still connecting from the same IP: 10.0.0.2 in my case

nginx fore example sees the users real ip

could you fix this or is this a "BungeeCord in a container" problem?

**Comment by itzg** [comment]
It's the latter. It's beyond the container's control. Using host networking might solve it.
