### ISSUE TITLE
[FEAT] Tag published images

### ISSUE THREAD

**Issue by orblazer** [itzg/docker-bungeecord#27]
Hello,
I make that issue for propose to tag the images when is published.

That is useful for fix version of image without pass the hash like `itzg/bungeecord:latest@sha256:fd084c6d9a456226e3c17e2318a47db2fd7842a171709c20dc03b0e0211ff888`.

Thanks.

**Comment by itzg** [comment]
Sorry for the delay. I discovered I already had my DockerHub build setup for tags, so `itzg/bungeecord:1.2.0` is now available with your changes.
