### ISSUE TITLE
Use the Paper Parchment API instead of CI

### ISSUE THREAD

**Issue by Proximyst** [itzg/docker-bungeecord#28]
PaperMC recommends the use of their Parchment API instead of using the CI directly.

For Waterfall, this would be:

- https://papermc.io/api/v1/waterfall/1.16/latest - JSON of information on the latest build
- https://papermc.io/api/v1/waterfall/1.16/latest/download - The file itself. This uses a `Content-Disposition` header, so you can safely download without redirecting the filename, but I reckon that will be wanted.

**Comment by itzg** [comment]
Good find! I'll work on incorporating that.
