### ISSUE TITLE
Possible HEALTHCHECK using Dinnerbone/mcstatus

### ISSUE THREAD

**Issue by jaecam** [itzg/docker-bungeecord#3]
For the sake of consistency, adding an identical (or similar) healthcheck to this image would be a good idea. I'm making this an issue rather than a PR right away because I need to test whether the library works with Bungee proxies. I'm assuming it does, but looking at some of the handshaking code used in Dinnerbone's lib, it's probably a good idea to test it before going to a PR.

**Comment by itzg** [comment]
Ah, good idea. Are you planning on trying to address this (which would be much appreciated) or want me to?

**Comment by NynjaCypher** [comment]
I'm going to just check the library today before making a PR.

**Comment by NynjaCypher** [comment]
Not sure if it's local, but I can't seem to start up a container today for this image. :P
`Downloading https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
curl: (23) Failed writing body (0 != 568)
ERROR: failed to download`

**Comment by NynjaCypher** [comment]
Yeah, for some reason curl's throwing a permission denied error. I've tried changing the ownership and modes of the server directory, however it doesn't seem to really affect it :P. Staying as root user fixes the issue, however it does mean you're running under a root user.

**Comment by NynjaCypher** [comment]
Due to bbae07a's change in user initialization, some modifications are going to be needed, possibly just reverting to its parent commit.

**Comment by NynjaCypher** [comment]
I've just utterly confused myself haha. If you don't mind @itzg, I would greatly appreciate any help getting this fixed.

**Comment by itzg** [comment]
:) Yep, I'll take a look when I get settled at a keyboard. UIDs and volume attachment are still an annoying balancing act in docker.

**Comment by NynjaCypher** [comment]
Thanks :P Hope you get somewhere with this, unlike my efforts. :PP

**Comment by itzg** [comment]
Health checks with mc-status got included at some point.
