### ISSUE TITLE
Feature request: copy `waterfall.yml`, `modules.yml` and `server-icon.png` from /config to /server if exists.

### ISSUE THREAD

**Issue by k-jiang** [itzg/docker-bungeecord#30]
We are trying to use this docker image for a Waterfall server. We want to be able to customize settings in `waterfall.yml`, `modules.yml` as well as uploading a `server-icon.png` to the container. But it seems that the startup script only copy 'config.yml' from volume /config to /server.

Can we have the ability to copy `waterfall.yml`, `modules.yml` and `server-icon.png` to /server if it is exists in the `/config` volume please? Thanks!

(P.S. we can do a PR on this if preferred)

**Comment by itzg** [comment]
Good idea. A PR would be great.
