### ISSUE TITLE
Add multiple java version and versionning tag

### ISSUE THREAD

**Issue by orblazer** [itzg/docker-bungeecord#38]
Hello,
Could publish the image with versioning and for different java version like https://github.com/itzg/docker-minecraft-server/ ?

Tahnks

**Comment by itzg** [comment]
Any particular Java version? Java 11?

**Comment by orblazer** [comment]
Yes java 11 should be great, because is new LTS version.

**Comment by itzg** [comment]
Sorry it has taken me so long to do anything with this; however, I was just thinking, is it probably safe enough to simply change the mainline `latest` image to be based on java 11? The `itzg/minecraft-server` image is somewhat stuck on 8 only because of Forge support.

**Comment by orblazer** [comment]
i think but this could break old versions of bungee ?

**Comment by itzg** [comment]
> i think but this could break old versions of bungee ?

Yeah, I really don't know either way.

Oh...apparently I did already setup branches for AdoptOpenJDK 11 and 13 and image tags for each

https://hub.docker.com/r/itzg/bungeecord/tags?page=1&ordering=last_updated&name=adopt

however, I'm still lacking the version-tag and merge mechanism that I have in `itzg/minecraft-server`

**Comment by orblazer** [comment]
ok, yes the version-tag could be very nice :+1:

**Comment by itzg** [comment]
Script is  now brought over and 1.5.0 tags published

https://hub.docker.com/repository/docker/itzg/bungeecord/tags?page=1&ordering=last_updated&name=1.5.0
