### ISSUE TITLE
Unhealthy Container

### ISSUE THREAD

**Issue by Janilom** [itzg/docker-bungeecord#42]
I am able to connect to the Waterfall proxy and the two servers connected to it. However I started getting an Unhealthy Container notification.  

failed to ping localhost:25577 : json: cannot unmarshal number -1 into Go struct field Version.version.protocol of type uint

**Comment by itzg** [comment]
I'll have to investigate that further, but for the time being you can disable the health check as described here

https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck

**Comment by itzg** [comment]
So far I haven't able to recreate this issue. Using this compose file

https://github.com/itzg/docker-bungeecord/blob/master/docs/docker-compose-waterfall.yml

I see the health reported as

```json
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2021-01-08T02:10:40.5938785Z",
      "End": "2021-01-08T02:10:41.5267142Z",
      "ExitCode": 0,
      "Output": "localhost:25577 : version=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x online=0 max=1 motd=''"
    }
  ]
}
```

May also want to compare with the config I'm using:

https://github.com/itzg/docker-bungeecord/blob/master/docs/config.yml

**Comment by Janilom** [comment]
It may be a plugin causing it. I had started adding them when the issue started, I'll remove them and test it without.

I'm not sure if I can ask some other questions here or if I should stay on the original topic but I'm working with dynmap plugin and I would like to add it to a MySQL db by just having the info in my compose file but I am having trouble getting the plugin to connect to the DB. The plugin is in one of the worlds that is setup in the bungeecord compose file.

db:
    environment:
      - MYSQL_USER=minecraft
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=MCdb

bungeecord
      - DB_USER=minecraft
      - DB_HOST=localhost:3365
      - DB_PORT=3365
      - DB_NAME=MCdb
      - DB_PASSWORD=password

plugin config
  type: mysql
  hostname: localhost
  port: 3365
  database: MCdb
  userid: minecraft
  password: password

**Comment by itzg** [comment]
Feel free to post here if you identify which plugin it is, since that'll help others that come across this issue.

As for the other question: change "localhost" in the `DB_HOST` to point at your "db" service by using "db:3365". localhost/127.0.0.1 within a container is namespaced to only be useful within the container (or pods in kubernetes).

**Comment by Janilom** [comment]
Okay I have compose files configured properly. Do the config files in the plugins need to point to the same compose information or should they have the default localhost:3306 and just add the userid/password?

**Comment by itzg** [comment]
They all need to be changed since "db" is the hostname of your MySQL container. In Docker you pretty much want to treat "localhost" as being useless. 

The rcon tool I provide is a notable exception since it hits the Minecraft server at localhost since you exec it within the container and therefore within same networking namespace.

**Comment by Janilom** [comment]
The plugin that was causing the issue was AdvancedNMotd. I noticed that the player count was not showing properly on the Minecraft server selection screen so I checked their documentation to see what the issue was. 

The solution was to open the AdvancedNMotd plugin config.yml and change the "Version: true" to false.


As for my database issue, I am able to use the db for permissions with LuckPerms without changing anything else. I cannot however get dynmap or other plugins that have their own configuration files to use the database. Not sure what I am doing wrong but they just won't connect to it.

**Comment by itzg** [comment]
> As for my database issue, I am able to use the db for permissions with LuckPerms without changing anything else. I cannot however get dynmap or other plugins that have their own configuration files to use the database. Not sure what I am doing wrong but they just won't connect to it.

What logs, if any, do they provide when failing to connect?

**Comment by SinanAkkoyun** [comment]
Hi, I encounter the same issue.
Failure count of 1457 after an uptime of 12h. I host a server with around 50 players
This is the error it shows:
failed to ping localhost:25577 : could not connect to Minecraft server: dial tcp 127.0.0.1:25577: connect: connection refused
```yml
# Proxy
  mc-proxy:
    image: itzg/bungeecord
    ports:
      - 25565:25577
    restart: always
    tty: true
    stdin_open: true
    environment:
      TYPE: WATERFALL
      MEMORY: "2G"
      MAX_MEMORY: "8G"
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_DB_HOST: "db-proxy"
      CFG_DB_NAME: "proxy"
      CFG_DB_USERNAME: "proxy"
      CFG_DB_PASSWORD: "${DB_PROXY_PASSWORD}"
    volumes:
      - "${MINECRAFT_PATH}/proxy/server:/server"
```

Does this health check refer to pinging the external port forward? Because it pings localhost:25577 and not mc-proxy:25577, it shall ultimately ping localhost:25565 or mc-proxy:25577

**Comment by itzg** [comment]
Health check is declared here

https://github.com/itzg/docker-mc-proxy/blob/master/scripts/health.sh

Default for SERVER_PORT is 25577 since that is the default for bungee/velocity.

**Comment by twkonefal** [comment]
Understood. My relative unfamiliarity with docker made this part of the configuration/documentation unclear.  Thank you.

**Comment by itzg** [comment]
FYI that wasn't a docker thing. The default is 25577

https://docs.papermc.io/velocity/configuration#address

**Comment by twkonefal** [comment]
The docs on the main github page (https://github.com/itzg/docker-mc-proxy) don't mention the SERVER_PORT ENV variable. I had no idea it could even be set there. Would it be possible to add that to the documentation?

**Comment by itzg** [comment]
That's fair. I can add that to https://github.com/itzg/docker-mc-proxy#ports

**Comment by itzg** [comment]
`SERVER_PORT` is now documented and health check will also inspect `velocity.toml` to identify the port to examine.
