### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-bungeecord#45]
Hey, any chance of a helm chart for this one?

Thanks

**Comment by itzg** [comment]
Good idea and should be quite doable. I'll plan on adding to the helm repo https://github.com/itzg/minecraft-server-charts

**Comment by ChipWolf** [comment]
Wrote one for your bungee container today, feel free to nick it. I used essentially all of the same principals as your other charts, would be good to iterate on :) https://github.com/ArchitectSMP/charts

**Comment by itzg** [comment]
Looks very nice! It would be super awesome if you PR'ed that into the https://github.com/itzg/minecraft-server-charts repo. I can stitch together the CI bits, but at least a PR would give you proper contributor credit.

**Comment by ChipWolf** [comment]
itzg/minecraft-server-charts#50
