### ISSUE TITLE
Repo does not exist

### ISSUE THREAD

**Issue by tnazarowski** [itzg/docker-bungeecord#46]
Forgive me if I'm missing something that's much more simple.   As of about 24 hours ago, the repo [itzg/docker-bungeecord:latest] does not appear to exist.  The same issue does not appear with the itzg/minecaft-server image.  Both of which are awesome.

Unable to find image 'itzg/docker-bungeecord:latest' locally
docker: Error response from daemon: pull access denied for itzg/docker-bungeecord, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by itzg** [comment]
You're in luck, it is indeed something simple: the image name doesn't have the "docker-" prefix that I put on the repo naming. 

https://hub.docker.com/r/itzg/bungeecord
