### ISSUE TITLE
Clean up old jars following upgrades

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-bungeecord#47]
If the proxy version changes, the old jar sticks around.
Especially if you allow the container to pull the latest jar on start, this makes some mess.

This is a feature request to clean up following upgrades.

**Comment by thenilsdev** [comment]
Same problem here. Would be nice to have `REMOVE_OLD_MODS`, `REMOVE_OLD_MODS_INCLUDE` and `REMOVE_OLD_MODS_DEPTH` from https://github.com/itzg/docker-minecraft-server/blob/7164d2b8857d9e16c1ee2b01290df69ad019632e/start-spiget#L48-L52 and https://github.com/itzg/docker-minecraft-server/blob/cc204c297fde35fb30d2a9fa2741aa9f28f2dd8e/start-utils#L178-L182

**Comment by itzg** [comment]
Both are good requests.

**Comment by ChipWolf** [comment]
> 
> 
> Same problem here. Would be nice to have `REMOVE_OLD_MODS`, `REMOVE_OLD_MODS_INCLUDE` and `REMOVE_OLD_MODS_DEPTH` from https://github.com/itzg/docker-minecraft-server/blob/7164d2b8857d9e16c1ee2b01290df69ad019632e/start-spiget#L48-L52 and https://github.com/itzg/docker-minecraft-server/blob/cc204c297fde35fb30d2a9fa2741aa9f28f2dd8e/start-utils#L178-L182

`GENERIC_PACK` does this with a manifest already

**Comment by itzg** [comment]
@ChipWolf I believe @thenilsdev meant the same kind of functionality from the minecraft server image would be helpful over here.

@thenilsdev can you go ahead an open a separate issue for your request?

**Comment by ChipWolf** [comment]
> 
> 
> @ChipWolf I believe @thenilsdev meant the same kind of functionality from the minecraft server image would be helpful over here.
> 
> @thenilsdev can you go ahead an open a separate issue for your request?

Oh, I didn't look at the repo title 😄 yeah that could be ported over

**Comment by ChipWolf** [comment]
destale

**Comment by itzg** [comment]
The latest image now cleans up older jars. Please re-open and let me know if you find something wrong.
