### ISSUE TITLE
proxy_protocol option breaks health check

### ISSUE THREAD

**Issue by thenilsdev** [itzg/docker-bungeecord#51]
In a Docker environment with a HAProxy the `proxy_protocol` setting is essential, unfortunately then mc-status does not work anymore. Is there a possibility to extend mc-status with query packets or to implement the protocol adjustments optionally?

If this is the wrong place, I'm happy to create the issue directly in the mc-status github issue area

**Comment by itzg** [comment]
I didn't realize bungeecord had an option for PROXY protocol. A change will be needed for both repos, so I also created https://github.com/itzg/mc-monitor/issues/6

**Comment by itzg** [comment]
I have added a variable called `HEALTH_HOST` that defaults to localhost, but in your case could be changed to point at the HAproxy's host/IP address. Would that work?

**Comment by thenilsdev** [comment]
I don't think this is a solution, because the HAProxy distributes the requests to all proxy servers at the same time, meaning if one proxy is offline all are classified as unhealthy

**Comment by itzg** [comment]
Oh, so you have several equivalent replicas of bungeecord instances behind HAproxy?

**Comment by thenilsdev** [comment]
Exactly. Distributed across multiple hosts

**Comment by itzg** [comment]
This is getting harder than I thought. It'll take an enhancement in https://github.com/Raqbit/mc-pinger also -- so three repos will need to be touched.

**Comment by itzg** [comment]
FYI, have a PR submitted ^

**Comment by itzg** [comment]
The latest image now includes the variable `HEALTH_USE_PROXY`, which you'll want to set to "true".

**Comment by thenilsdev** [comment]
Got `/bin/sh: 1: /health.sh: Permission denied`

**Comment by itzg** [comment]
Oops, try the latest image now.

**Comment by thenilsdev** [comment]
I don't know if this is related but on our production system (without HAProxy) the newest image doesn't start anymore `sudo: /usr/lib/jvm/java-1.8-openjdk/bin/java: command not found`. 

Please give me feedback if I should create an issue for this.

On the HAProxy system the healthcheck runs now without problems, many thanks!

**Comment by itzg** [comment]
Are you using Portainer or something similar? If so, that product has an issue with incorrectly retaining image declared variables like PATH and JAVA_HOME. As a result, image upgrades that involve a change to those variables (like switching to Java 11) are not handled properly.

**Comment by thenilsdev** [comment]
Has clarified, thank you very much!
