### ISSUE TITLE
Keeping all branches in sync

### ISSUE THREAD

**Issue by thenilsdev** [itzg/docker-bungeecord#57]
For example, the java8 branch does not yet have the correct permissions set for `health.sh`. The same is true for the README changes. Is this handled with the tags/releases and `docker-versions-create.sh`?

**Comment by itzg** [comment]
Yes, I need to re-run that script to merge things over. That's also the process that messed with the java8 base image stuff 😀

**Comment by itzg** [comment]
Latest changes are merged and tagged now.
