### ISSUE TITLE
Plugins folder only copy newer files

### ISSUE THREAD

**Issue by weihao** [itzg/docker-bungeecord#59]
```
if [ -d /plugins ]; then
    echo "Copying BungeeCord plugins over..."
    cp -r /plugins $BUNGEE_HOME
fi
```

Add a `-u` update flag to the operation to avoid overwrites in this scenerio:

1. initialize container 
2. plugins copied over
3. saved user-generated data to plugins folder
4. container restarts
5. plugins folder copied over and overwrite all the data

**Comment by itzg** [comment]
Excellent point. Want to submit a PR?

**Comment by weihao** [comment]
Sure, submitting a patch

**Comment by weihao** [comment]
https://github.com/itzg/docker-bungeecord/pull/60
