### ISSUE TITLE
Connection limit

### ISSUE THREAD

**Issue by m4l3vich** [itzg/docker-bungeecord#6]
I'm using this image in pair with [itzg/minecraft-server](https://hub.docker.com/r/itzg/minecraft-server/) and I can't have more than 10 users connected to one BungeeCord container. When I'm having 2 BungeeCord instances leading to one PaperSpigot server, I can have 20 players connected to it. I'm also using Docker's internal bridge network to make contact between these containers. Here's a screenshot of this problem:
![image](https://user-images.githubusercontent.com/23311163/40465517-a426aafc-5f53-11e8-8d27-ef6e431b55e9.png)

**Comment by Deniom** [comment]
I also encountered such a problem, I thought I was doing something wrong

**Comment by m4l3vich** [comment]
It seems that the reason of issue was `bridge` type network. There's no problem appearing when using `host` networking.
