### ISSUE TITLE
API Update PaperMC

### ISSUE THREAD

**Issue by yogi7777** [itzg/docker-bungeecord#61]
Hi, 

Have you this in focus? https://discord.com/channels/289587909051416579/492517675680006144/844716870904971275 

This is a reminder that version 1 of the PaperMC downloads API is deprecated and will be removed in the future - please move to using version 2  of the downloads API to avoid service interruptions.

Is this a problem?

Actually they have a maintenance problem and waterfall doesn't start.

**Comment by itzg** [comment]
I am using v2 of the Paper API

https://github.com/itzg/docker-bungeecord/blob/a9017f2fd89629daffb8918846c4d4dba070721f/run-bungeecord.sh#L62

Have you found a place where it isn't?

**Comment by yogi7777** [comment]
hi, thanks for your info. No I was not sure. then is all ok :) thanks for your work.
