### ISSUE TITLE
Timeout Reached

### ISSUE THREAD

**Issue by BananaBlu77** [itzg/docker-bungeecord#64]
I start the container and in the logs I see this:
```
Downloading https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
curl: (28) Timeout was reached
ERROR: failed to download

```

**Comment by itzg** [comment]
The generated URL is valid, so it seems to be something about your Docker/host networking.

**Comment by BananaBlu77** [comment]
I'm on a Raspberry Pi 4 running RaspberrypiOS (debian buster) and I can't resolve that issue. Can you help me?

**Comment by itzg** [comment]
Ah, you'll probably need to apply the same fix as this

https://github.com/itzg/docker-minecraft-server/issues/755#issuecomment-781615497

**Comment by BananaBlu77** [comment]
Ok, it worked.
