### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by erahhal** [itzg/docker-bungeecord#66]
Hi, just tried the latest (saw you pushed 4 hours ago or so), and getting the following error:

`ERROR: for bungeecord  Cannot start service bungeecord: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/run-bungeecord.sh": permission denied: unknown`

Is this a permissions issue during the build of the docker container?

EDIT: I built the image locally after setting +x on `run-bungeecord.sh` and it at least starts up now, though it's saying that it's unhealthy.  Looking into it.

EDIT2: It's working, depite the "unhealthy" message in `docker ps`

**Comment by itzg** [comment]
Oops, I temporarily renamed the file and since I develop on Windows it messes with exec permissions. I'll get that fixed ASAP.

**Comment by itzg** [comment]
Sorry about that. The image published now fixes that.

**Comment by erahhal** [comment]
Thanks for the quick response!
