### ISSUE TITLE
Java 16 (and eventually Java 17) Image Support

### ISSUE THREAD

**Issue by Davie3** [itzg/docker-bungeecord#67]
With Mojang's decision to make Minecraft 1.17 require Java 16 or later and servers like Spigot/Paper following suite, Java 16+ will be required for some plugins to continue to function even on Bungeecord. The ViaVersion plugin is already one I have seen give Java version warnings.

This is a feature request to have Java 16+ Images available.

**Comment by Davie3** [comment]
Also as an aside, the work you do here and on itzg/minecraft-server is much appreciated! I can't thank you enough for dedicating so much time and effort to these Minecraft Docker Containers!

**Comment by itzg** [comment]
You're welcome!

I wonder if it's safe to simply shift the main/latest image to Java 16. I suppose if any issues come up I can create variant images as needed.

**Comment by itzg** [comment]
The latest image is now based on Java 16

**Comment by Davie3** [comment]
Wonderful! Testing the latest image now. Everything seems to be functioning so far.
