### ISSUE TITLE
Error on startup using Velocity

### ISSUE THREAD

**Issue by bmnijhuis** [itzg/docker-bungeecord#68]
When starting the container I het the following in the log: Warning: Illegal date format for -z, --time-cond (and not a file name). This is the first part of the debug log containing the error

	[init] Resolving type given VELOCITY,
	[init] Downloading https://versions.velocitypowered.com/download/latest.jar,
	+ extraCurlArgs=(-v),
	+ log 'Resolving type given VELOCITY',
	+ echo '[init] Resolving type given VELOCITY',
	+ case "${TYPE^^}" in,
	+ : latest,
	+ BUNGEE_JAR_URL=https://versions.velocitypowered.com/download/latest.jar,
	+ BUNGEE_JAR=/server/Velocity-latest.jar,
	+ isTrue true,
	+ local value=true,,
	=,
	+ case ${value} in,
	+ result=0,
	+ return 0,
	+ '[' -f /server/Velocity-latest.jar ']',
	+ zarg='-z '\''/server/Velocity-latest.jar'\''',
	+ log 'Downloading https://versions.velocitypowered.com/download/latest.jar',
	+ echo '[init] Downloading https://versions.velocitypowered.com/download/latest.jar',
	+ curl -o /server/Velocity-latest.jar -z ''\''/server/Velocity-latest.jar'\''' -fsSL  https://versions.velocitypowered.com/download/latest.jar,
	Warning: Illegal date format for -z, --time-cond (and not a file name). ,
	Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.,
	+ '[' -d /plugins ']',
	+ [[ -n '' ]],
	+ [[ -n '' ]],

**Comment by itzg** [comment]
Sorry about that. It should now be fixed in the latest image.

**Comment by bmnijhuis** [comment]
I did a quick test and it is fixed. Thanks for the effort!
