### ISSUE TITLE
container not listening to provided container

### ISSUE THREAD

**Issue by olesien** [itzg/docker-bungeecord#7]
Hi,
So we have managed to get bungeecord working on 25565, however.. it seems like it's just running not caring about when we change the config and doesn't really load the plugins in bungeecord. It's all simply just default. 
This is our docker-compose-yml:
https://justpaste.it/7gbgy

Could you help us with this? Thanks

**Comment by olesien** [comment]
Hm yeh I did take a look at that earlier, however with little success. Can you give me a version of the one I pasted however probably working (all work just fine but the bungeecord one). It would be much appreciated :)

**Comment by olesien** [comment]
I tried like this aswell, same results:

bungee-server:
  ports:
    - "25565:25577"
  volumes:
    - /home/timli168/creative:/server
    - /home/timli168/creative:/plugins
  environment:
    EULA: "TRUE"
    INIT_MEMORY: "1G"
    MAX_MEMORY: "2G"

  image: itzg/bungeecord

  container_name: bungee

  tty: true
  stdin_open: true
  restart: always

**Comment by olesien** [comment]
What it looks like right now:
bungee-server:
  ports:
    - "25565:25577"
  volumes:
    - /home/timli168/bungee:/config.yml
  environment:
    EULA: "TRUE"
    INIT_MEMORY: "1G"
    MAX_MEMORY: "2G"

  image: itzg/bungeecord

  container_name: bungee

  tty: true
  stdin_open: true
  restart: always


I also have had it: exactly as the one you showed (like that part), however having it output an error saying that /server/config.yml doesn't exist, and a bunch of others.

**Comment by itzg** [comment]
Have you created the file `config.yml` in your `/home/timli168/bungee` directory already? If so, the volume mapping would be:

```
    volumes:
      - /home/timli168/bungee/config.yml:/server/config.yml
```

Are you using `docker-compose` or `docker stack deploy` to deploy the compose file?

**Comment by olesien** [comment]
I'm using docker-compose.yml. I put it inside of timli168 and run the command docker-compose up -d

**Comment by olesien** [comment]
What I got when running it now (those two lines are the ones you did :P 
https://gyazo.com/1fe5cb112308e747482eb01df6f1baec

**Comment by olesien** [comment]
What the docker-compose file looks like now:
https://justpaste.it/4ggcl
(spaces don't work inside of that website, they are spaced correctly)

**Comment by olesien** [comment]
What /home/timli168/bungee looks like:
https://gyazo.com/91444e6cc6975c1f47e47ebfd0682c76

**Comment by itzg** [comment]
It’s ok, I don’t use bungeecord that much so I have to re-learn how to use it each time.

**Comment by olesien** [comment]
Wait.. are you just giving up? Also, that example docker, is it working as it is? Why does it not specify where the server is at?

**Comment by itzg** [comment]
I'm still working on a better example that closer matches your scenario. I was just clarifying that I'm a little slow to help with the bungeecord issue since I don't readily have examples other than the one in the repo.

**Comment by olesien** [comment]
No problem ;) How long do you expect it to take?

**Comment by itzg** [comment]
@olesien here is a more complete example with a lobby and three varying servers:

https://gist.github.com/itzg/fa64a1686dd5b4a2a768202676111ed1

FYI, rather than vary the port for each, I leave them all at the default 25565 and in the `servers` section here

https://gist.github.com/itzg/fa64a1686dd5b4a2a768202676111ed1#file-config-yml-L18-L34

I ensure the "hostname" matches up with the service name from the compose file.

**Comment by olesien** [comment]
Thank you very much! ;) have you tested it though?

**Comment by olesien** [comment]
Thanks, it works now ;) (since it kept giving me shit after doing everything by that, I reset everything making those servers instead etc, and it works now. There is one problem that remains though, which is why I did this in the first place: the first time you search for the servers in minecraft, it says that it's not connectable, it however is (and if you search again it works). Is this anything that you even can fix or is this simply.. Not possible?

**Comment by olesien** [comment]
Okay works now. What should I add to bungeecord so that it finds the plugin folder aswell?

**Comment by olesien** [comment]
Thanks for fixing it.. For some reason there are however a few other REALLY annoying issues.. First: Everyone on the server is treated the exact same, so I can't do any things even though I have op and a group in pex that should allow me to do anything.  docker attach <server> does seem to work at first, as you do get info like for example when I type something in chat. Although you can type things and press enter, they don't register at all, like if I normally type "op olesien", it'll say so. However it doesn't (and I also don't get oped)

**Comment by olesien** [comment]
Okay so based on my understanding, it's something fucked up with the uuid or such

**Comment by olesien** [comment]
It did work just fine before sooo

**Comment by olesien** [comment]
When running a normal bungeecord server on my pc, I can see that proxy.log.0.yml along with proxy.log.0.lck.yml get created. Maybe these need to be able to be updated?

**Comment by itzg** [comment]
Yes, the `/server` directory is a regular Linux directory inside of the container. The container startup script does pull down the latest version of bungeecord, so perhaps there's a bug in their code. That's only speculation, so when I get chance tonight or tomorrow I'll try out the "op" commands to see if I can learn more about bungee configuration.

**Comment by itzg** [comment]
That’s great to hear about the progress. The “op” scenario is something I can possibly help look at; however, since it used to work for you before can you provide a config.yml and server.properties (from server side) that used to work? What version and flavor of server jar were you using that worked?

**Comment by olesien** [comment]
With op scenario you mean the docker attach issue I suppose. I always use spigot and not bukkit or vanilla. (Vanilla is the one without plugins. Spigot is the one that works best with bungeecord). I can't really provide those two atm (server.properties is pretty irrelevant though). I am pretty certain that it is either something either with the ports or missing setting in docker compose (I remember something about tty = true for example, you can take a look at the top of this thread.
Could you please try out yourself and see if it works for you? (With spigot preferably)

**Comment by itzg** [comment]
That's a good point -- I have been experimenting with vanilla backends, but not with spigot. I'll give that a shot and see if I can make any progress.

As for the "op scenario" I just meant where you mentioned
> it has no idea where it's supposed to send the information like ("op olesien") and therefore not recieve anything like ("opped olesien")

Like you said, it might end up being a TTY/console type setting. To clarify, you're expecting to see that in the container logs or back in the Minecraft client view? Likewise, are you running the `op` command and others via the server console or within the client with a `/op`?

**Comment by itzg** [comment]
Aha, you provided exactly the right clue. I was able to see the same problem when I ran a container via docker-compose (vs a `docker run`) and the solution for me was adding the `stdin_open: true` such as this line

https://gist.github.com/itzg/9f97a77e3461116f024f7a2c9c64d03d#file-docker-compose-yml-L15

**Comment by olesien** [comment]
Good job! ;) Thank you very much for helping me with these issues even though you could have just not replied ;)
