### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by alvarlagerlof** [itzg/docker-bungeecord#73]
https://github.com/itzg/docker-minecraft-server allows running stop -i to shut down gracefully (no kill). The timeout there is also nice. I am missing here. Could it be added?

**Comment by alvarlagerlof** [comment]
Hmm. Considering I don't have this issue with https://github.com/itzg/docker-minecraft-server, it may be something else. How does the `STOP_SERVER_ANNOUNCE_DELAY` work there?

**Comment by itzg** [comment]
It's actually handled by https://github.com/itzg/mc-server-runner, but I'm now realizing that should work here too.

**Comment by alvarlagerlof** [comment]
Yeah I went on a little dig for the parameters, and found that too. Both are servers running on JVM and you can interact with both using RCON, so lots of similarities. 

One thing to consider if you choose to implement the mc runner here too is potential duplicates messages. You want to keep both up for the same amount of time, but both sending messages might not be good. 

I'd want to keep the messages per server I think. There are potential use cases for keeping the lighter proxy up while shutting down the servers.

Just a sleep(env param) here before stop would solve my issue.

**Comment by alvarlagerlof** [comment]
Just done a lot of experimenting with systemd trying to get /bin/sleep in before it stops. I can't seem to do it.

**Comment by alvarlagerlof** [comment]
Still have not found a good solution. Most important is that it works for servers, which it does, so data loss is avoided, but this ends up being a bad experience in game.
