### ISSUE TITLE
Don't set or allow setting automatic jvm memory

### ISSUE THREAD

**Issue by alvarlagerlof** [itzg/docker-bungeecord#74]
Following up from https://github.com/itzg/docker-minecraft-server/issues/742 I think this would also benefit from something similar, since it is after all, also in a container.

**Comment by alvarlagerlof** [comment]
https://github.com/itzg/docker-bungeecord/blob/master/run-bungeecord.sh This is the file where it is set. I ran a small instance, and have had trouble likely to that.

**Comment by itzg** [comment]
The latest image now lets `MEMORY` be unset.

**Comment by alvarlagerlof** [comment]
Kind of missing `--env JVM_XX_OPTS="-XX:MaxRAMPercentage=X` here now

**Comment by itzg** [comment]
> Kind of missing `--env JVM_XX_OPTS="-XX:MaxRAMPercentage=X` here now

Ah yes, I keep updating the other repo and forgetting the same here.

**Comment by itzg** [comment]
Updated the README

**Comment by alvarlagerlof** [comment]
This env var does not have the XX in it, unlike the one for the mc server (which has one without and on with. Does that mean something?

**Comment by itzg** [comment]
There wasn't a need for it before 😃, but I'll add that.
