### ISSUE TITLE
403 on download core

### ISSUE THREAD

**Issue by IcrusaI** [itzg/docker-bungeecord#75]
Error 403 appears when downloading bungeecord. I requested it through curl, it turned out to ask to pass a captcha.
![image](https://user-images.githubusercontent.com/20923066/139944625-106b1dcc-1777-43a4-a86d-824cfebfcb31.png)

**Comment by itzg** [comment]
Hmm, will need to research if they have a direct/cdn URL...

**Comment by itzg** [comment]
Actually, it worked fine for me. Can you run this command and provide the output:

```
docker run --rm --entrypoint curl itzg/bungeecord -o /server/BungeeCord-lastStableBuild.jar -fsSL -v https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
```

where mine produced:
```
*   Trying 172.67.71.53:443...
* TCP_NODELAY set
* Connected to ci.md-5.net (172.67.71.53) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2292 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=md-5.net
*  start date: Jun  7 00:00:00 2021 GMT
*  expire date: Jun  6 23:59:59 2022 GMT
*  subjectAltName: host "ci.md-5.net" matched cert's "*.md-5.net"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x559a2603cc80)
} [5 bytes data]
> GET /job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar HTTP/2
> Host: ci.md-5.net
> user-agent: curl/7.68.0
> accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
< HTTP/2 200
< date: Wed, 03 Nov 2021 01:05:14 GMT
< content-type: application/java-archive
< content-length: 14794318
< x-content-type-options: nosniff
< content-security-policy: sandbox; default-src 'none'; img-src 'self'; style-src 'self';
< x-webkit-csp: sandbox; default-src 'none'; img-src 'self'; style-src 'self';
< x-content-security-policy: sandbox; default-src 'none'; img-src 'self'; style-src 'self';
< last-modified: Sat, 09 Oct 2021 07:13:38 GMT
< expires: Sat, 09 Oct 2021 07:13:38 GMT
< cache-control: max-age=14400
< cf-cache-status: REVALIDATED
< accept-ranges: bytes
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=LbKK0MotI7dNfhfuInmVo7bKT%2Bz9%2BSUt%2Bdp8Fbw7NeRCbflVP1McxtU9noJRVG%2Fa2R07Plvr1tdf33Rt%2FVYnEDAkSIUtWonRn326qPV1Ey3%2BssvG%2FoF6KxsDi%2Fs2"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 6a81b17148935e84-IAD
<
{ [612 bytes data]
* Connection #0 to host ci.md-5.net left intact
```

**Comment by IcrusaI** [comment]
`
root@vm273946:~# docker run --rm --entrypoint curl itzg/bungeecord -o /server/BungeeCord-lastStableBuild.jar -fsSL -v https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
*   Trying 104.26.14.18:443...
* TCP_NODELAY set
* Connected to ci.md-5.net (104.26.14.18) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2292 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=md-5.net
*  start date: Jun  7 00:00:00 2021 GMT
*  expire date: Jun  6 23:59:59 2022 GMT
*  subjectAltName: host "ci.md-5.net" matched cert's "*.md-5.net"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x55f680d40e10)
} [5 bytes data]
> GET /job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar HTTP/2
> Host: ci.md-5.net
> user-agent: curl/7.68.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
* The requested URL returned error: 403 
} [5 bytes data]
* stopped the pause stream!
* Connection #0 to host ci.md-5.net left intact
curl: (22) The requested URL returned error: 403 
`

**Comment by itzg** [comment]
Ours seemed to diverge at

```
* The requested URL returned error: 403 
```

but that's not where in the curl output I would expected that. Are you using an HTTP proxy or tunnel?

**Comment by IcrusaI** [comment]
No. This is the VPS I rented on the same day this problem occurred. https://pq.hosting/ . The server is located in Moscow

**Comment by itzg** [comment]
The image is working fine, so sounds like you need to ask that VPS provider to help.

**Comment by IcrusaI** [comment]
Good. Thank you. Waterfall, by the way, downloaded normally.
