### ISSUE TITLE
Copy more files then defined to the `/server` directory

### ISSUE THREAD

**Issue by anthr76** [itzg/docker-bungeecord#79]
I'm running this in kubernetes but having a hard time making it stateless. Basically I'm using luckperms + backed by a db and need to give the config.yml before start up. Though the secret is owned by root. So the process can no longer access it. My feature request is we can copy more folder from `/config` then what is already defined or better yet share some of the functions from the minecraft container

**Comment by anthr76** [comment]
For example:

https://github.com/itzg/docker-minecraft-server/blob/2c7796ea0b0e712bffc6b3559bedecfc6471d02e/scripts/start-setupMounts#L58-L69

**Comment by itzg** [comment]
I'm totally open to that. I was fixing an issue in there just yesterday and couldn't remember why it was so selective about what files were brought over. Like you said, I'll work on having it use the same mechanism.

**Comment by itzg** [comment]
The latest image will now sync everything in `/config` over to `/server`.

**Comment by itzg** [comment]
...and pushed another image update that performs placeholder variable processing of the files sync'ed over from `/config`.

**Comment by anthr76** [comment]
This did exactly what I needed :)

```
[mc-image-helper] 00:58:42.293 INFO  : Interpolating /config/velocity.toml -> /server/velocity.toml
[mc-image-helper] 00:58:42.300 INFO  : Interpolating /config/plugins/luckperms/config.yml -> /server/plugins/luckperms/config.yml
```

Soon I'll try the CFG replacments. For now I'm sending a pre-filled secret. Thanks!
