### ISSUE TITLE
unicode characters are not displayed correctly in logs

### ISSUE THREAD

**Issue by weihao** [itzg/docker-bungeecord#83]
https://github.com/PaperMC/Velocity/issues/603

hey, wanted to raise this issue here and see if we could find a solution to this encode error.

```
smp_1             | [06:45:40 INFO]: <.HuangFuSL> ������������������������
smp_1             | [06:45:49 INFO]: <.NewBeeplus> ������������������������
smp_1             | [06:45:54 INFO]: <.NewBeeplus> ���������������
smp_1             | [06:45:54 INFO]: <.HuangFuSL> ���
```

**Comment by itzg** [comment]
I have no idea what you want me to do about this. Since Velocity team punted with "a user configuration issue" then I'll say the same here. There's very little to the container startup so feel free to inspect what you think my fault is.

**Comment by weihao** [comment]
Okay, after tracing through containers, provisioned virtual machine, wsl, and host OS, it turns out the wsl on my OS was acting up because it did not have the correct locale installed.

I guessed the issue must lie in any of them, and glad to solve it.

Thanks for the input @itzg
