### ISSUE TITLE
Access bungeecord console

### ISSUE THREAD

**Issue by Mondei1** [itzg/docker-bungeecord#9]
Is there any way to get access to the bungeecord console? With the minecraft container this is possible with `rcon-cli` as you know but this is not working for bungeecord.

Thanks in advance.

**Comment by itzg** [comment]
I didn't even think about that bungeecord would have a console just like the MC server itself. I'll have to research if bungeecord include rcon support. If it doesn't, you can include `-i -t` in the `docker run`, then you can always [docker attach](https://docs.docker.com/engine/reference/commandline/attach/) to the container to send the commands.

**Comment by Mondei1** [comment]
Thanks for that tipp. I'll try this soon.

**Comment by Jupiops** [comment]
Maybe it's a solution for you too: I'm using [Minecraft-SSHD | SSH for your Minecraft server! | Universal Support](https://www.spigotmc.org/resources/minecraft-sshd-ssh-for-your-minecraft-server-universal-support.71887/) to connect to the console

**Comment by Mondei1** [comment]
Uh, this sounds like a cool plugin to have. Thanks for that tipp.

**Comment by itzg** [comment]
I'm getting 502 right now. @Jupiops is that a plugin or a server executable? There is a better way a could implement ssh access if that's actually desired.

**Comment by Mondei1** [comment]
For me honestly, this issue is now kind of irrelevant because I'm not into Minecraft anymore. For Rcon on Bungeecord I found [this plugin](https://www.spigotmc.org/resources/bungeecord-rcon.5817) which provides Rcon support for Bungeecord, haven't tested it but it looks promising.

**Comment by itzg** [comment]
Lots of great alternatives, so I’ll close this out.
