### ISSUE TITLE
groups: cannot find name for group ID 2000

### ISSUE THREAD

**Issue by klutzydrummer** [itzg/docker-bungeecord#90]
I'm running this in my Kubernetes cluster using the helm chart.
https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft-proxy

 I configured everything and keep running into the following error the second the pod spins up:
groups: cannot find name for group ID 2000

it restarts and just gets stuck in a loop. I tried using the default values, but get the same error.

I also tried changing the fsgroup from 2000 to 1000, but then it complains that the volume I'm using is set to GID 2000, even when I annotate so it's set to 1000

I have no idea what I'm doing wrong here, and I can't find a root password to see how it would behave if I manually added a group with GID 2000

**Comment by klutzydrummer** [comment]
Just thought I'd leave more supplementary info:
No references to GID 2000 in any of the configs or anything I can find within kubernetes
here is the list of groups that populates when I'm in the pod's shell and run:
cat /etc/group

daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
bungeecord:x:1000:

I get the same list when running the command in the docker compose version, yet that one actually comes up and works

**Comment by itzg** [comment]
What kubernetes distribution are you using?

**Comment by klutzydrummer** [comment]
I'm using minikube at the moment, since I'm mainly practicing. But if the issue has to do with the k8 distro I've been considering changing things up due to some of the limitations I keep running up against

**Comment by itzg** [comment]
Thinking about it more, changing the fsGroup is probably the right approach, but the persistent volume probably need to deleted/recreated.
