### ISSUE TITLE
Custom JAR support for Velocity

### ISSUE THREAD

**Issue by BBaoVanC** [itzg/docker-bungeecord#92]
I see that I can set `BUNGEE_JAR_URL` for Bungeecord, but there doesn't seem to be a way to do it for Velocity. I can't just use `BUNGEE_JAR_URL` because then it'll try and pull the Bungeecord version of the rcon plugin, instead of the one for Velocity. And it would also be better anyways since it's a different project from Bungeecord/Waterfall.

**Comment by itzg** [comment]
Great idea. I'll get it queued up, but a PR is welcome too.

**Comment by itzg** [comment]
With the latest image you can use `TYPE=CUSTOM` and `BUNGEE_JAR_URL` or `BUNGEE_JAR`. If RCON is enabled the velocity plugin can be pre-installed by setting `APPLY_VELOCITY_RCON` to "true".

**Comment by BBaoVanC** [comment]
> With the latest image you can use `TYPE=CUSTOM` and `BUNGEE_JAR_URL` or `BUNGEE_JAR`. If RCON is enabled the velocity plugin can be pre-installed by setting `APPLY_VELOCITY_RCON` to "true".

It works, but I had to use `BUNGEE_JAR_FILE` instead of `BUNGEE_JAR` to tell it the file path.

**Comment by itzg** [comment]
I'm sorry, that was a typo. I meant `BUNGEE_JAR_FILE`, so I'm glad you discovered that.
