### ISSUE TITLE
Would be nice to add ICON and OVERRIDE_ICON environment variables

### ISSUE THREAD

**Issue by JAHMCR** [itzg/docker-bungeecord#95]
Hi! Could you please add the ICON environment variable so this docker image can also download the server icon from a URL exactly as the minecraft-server one does?

Thanks!

**Comment by itzg** [comment]
That sounds like a good idea. Do you know if bungee expects it to be the same name and type as Minecraft itself?

**Comment by JAHMCR** [comment]
Thanks for the quick response! Yep, exactly the same one from Minecraft, I copy-pasted one from a minecraft-server container, but I'd be awesome if you add it to the env variables!

**Comment by JAHMCR** [comment]
@itzg please don't forget the OVERRIDE_ICON, I didn't add it to the initial issue description. Thanks!

**Comment by itzg** [comment]
FYI a PR is welcome.
