### ISSUE TITLE
Would be nice to have `REMOVE_OLD_MODS`, `REMOVE_OLD_MODS_INCLUDE` and `REMOVE_OLD_MODS_DEPTH` 

### ISSUE THREAD

**Issue by itzg** [itzg/docker-bungeecord#96]
Same problem here. Would be nice to have `REMOVE_OLD_MODS`, `REMOVE_OLD_MODS_INCLUDE` and `REMOVE_OLD_MODS_DEPTH` from https://github.com/itzg/docker-minecraft-server/blob/7164d2b8857d9e16c1ee2b01290df69ad019632e/start-spiget#L48-L52 and https://github.com/itzg/docker-minecraft-server/blob/cc204c297fde35fb30d2a9fa2741aa9f28f2dd8e/start-utils#L178-L182

_Originally posted by @thenilsdev in https://github.com/itzg/docker-bungeecord/issues/47#issuecomment-846472535_

**Comment by ChipWolf** [comment]
`GENERIC_PACK` would be very useful

**Comment by itzg** [comment]
> `GENERIC_PACK` would be very useful

Can you create a new issue for that?

**Comment by ChipWolf** [comment]
Not stale
